# Kanagawa #
set -g mouse on

# tmux sensible at home
set -s escape-time 0
set -g history-limit 50000

set -g display-time 4000

set -g status-interval 5

# Increase status bar length to show full session names
set -g status-left-length 30


# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on


# Fix end/home for xterm-256color
# bind-key -n Home send Escape "OH"
# bind-key -n End send Escape "OF"

unbind r
bind r source-file ~/.tmux.conf
bind-key -r f run-shell "tmux neww ~/.config/scripts/tmux-sessionizer"
bind-key C-e run-shell "~/.config/scripts/edit-tmux-output"

# set -g default-terminal "xterm-256color"
# set-option -ga terminal-overrides ",xterm-256color:Tc"

set -as terminal-features ',xterm*:Tc'
set -as terminal-features ',xterm*:extkeys'
set -s extended-keys always
set-option -g set-clipboard on

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip"


run '~/.tmux/plugins/tpm/tpm'
